FROM python:3.10

WORKDIR /app

COPY requirements.txt ./

RUN pip install -r requirements.txt

RUN [ "python3", "-c", "import nltk; nltk.download('popular')" ]

COPY . .

EXPOSE 5000

CMD ["python", "app.py"]

